language: node_js
node_js:
  - 10

before_install:
  - npm install -g hexo-cli
install:
  - npm install

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: public
  target_branch: master
  on:
    branch: whats-blog
